# Generated by Django 5.0.6 on 2024-06-25 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_category_contact_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Category',
            new_name='category',
        ),
    ]
